Repository mozilla/DeepSpeech, pull requests merged in 2018-09, with the labels that each got.

#1523 Explicit mention of supported platforms; should infer no default Wind…
  README.md
Labels: documentation

#1553 Add CPP artifact deps
  taskcluster/scriptworker-task.yml
  taskcluster/simple-task.tyml
Labels: foundations

#1595 Enforce same sox options as libsox for C++ client
  native_client/javascript/client.js
  native_client/python/client.py
Labels: bug

#1600 Fixed a mismatched array new and delete
  native_client/trie_node.h
Labels: bug
