Repository mozilla/DeepSpeech, pull requests merged in 2020-02, with the labels that each got.

#2724 Print best and worst results in a WER report.
  evaluate.py
  evaluate_tflite.py
  util/evaluate_tools.py
  util/flags.py
Labels: enhancement

#2688 Specify upper frequency limit when computing Mfccs
  GRAPH_VERSION
  util/feeding.py
Labels: breaks-bw-compat

#2749 Explode tc-tests-utils into several smaller chunks
  taskcluster/.build.yml
  taskcluster/tc-all-utils.sh
  taskcluster/tc-all-vars.sh
  taskcluster/tc-android-utils.sh
  taskcluster/tc-asserts.sh
  taskcluster/tc-build-utils.sh
  taskcluster/tc-dotnet-utils.sh
  taskcluster/tc-lite_benchmark_model-ds-tests.sh
  taskcluster/tc-node-utils.sh
  taskcluster/tc-package.sh
  taskcluster/tc-py-utils.sh
  taskcluster/tc-tests-utils.sh
  taskcluster/tc-train-tests.sh
  taskcluster/test-linux-opt-base.tyml
  taskcluster/test-lite_benchmark_model-linux-amd64-opt.yml
  taskcluster/test-training_16k-linux-amd64-py35m-opt.yml
  taskcluster/test-training_16k-linux-amd64-py36m-opt.yml
  taskcluster/test-training_8k-linux-amd64-py36m-opt.yml
Labels: enhancement

#2755 Use other storage for TrainingSpeech dataset
  bin/import_ts.py
Labels: dataset

#2764 Support ElectronJS v8.0
  taskcluster/.shared.yml
  taskcluster/tc-all-vars.sh
  taskcluster/test-electronjs_v8.0-darwin-amd64-opt.yml
  taskcluster/test-electronjs_v8.0-win-amd64-opt.yml
  taskcluster/test-electronjs_v8.0_16k-linux-amd64-opt.yml
  taskcluster/test-electronjs_v8.0_8k-linux-amd64-opt.yml
Labels: enhancement

#2785 added ctc decoder builds tasks
  taskcluster/scriptworker-task-github.yml
Labels: good first bug

#2797 Doc: change cuDNN dependency to 7.6
  doc/USING.rst
Labels: documentation

#2802 Ensure sample rate comparison with proper types
  util/feeding.py
Labels: bug
