Repository mozilla/DeepSpeech, pull requests merged in 2020-04, with the labels that each got.

#2871 Automatically install ds_ctcdecoder in setup.py
  doc/TRAINING.rst
  setup.py
  taskcluster/tc-all-utils.sh
  taskcluster/tc-single-shot-inference.sh
  taskcluster/tc-train-tests.sh
  taskcluster/tc-transfer-tests.sh
  training/deepspeech_training/util/taskcluster.py
Labels: tests

#2868 Mention validate_label_locale in training doc
  doc/TRAINING.rst
Labels: documentation

#2882 Pr2876
  .gitignore
  doc/NodeJS-API.rst
  doc/NodeJS-Examples.rst
  doc/USING.rst
  doc/index.rst
  native_client/javascript/Makefile
  native_client/javascript/README.md
  native_client/javascript/client.ts
  native_client/javascript/index.d.ts
  native_client/javascript/package.json.in
  native_client/javascript/tsconfig.json
  taskcluster/tc-build-utils.sh
Labels: tests

#2889 Fix #2888: Use start-after / end-before for API example line references
  doc/C-Examples.rst
  doc/Java-Examples.rst
  doc/NodeJS-Examples.rst
  doc/Python-Examples.rst
  native_client/client.cc
  native_client/java/app/src/main/java/org/mozilla/deepspeech/DeepSpeechActivity.java
  native_client/javascript/client.ts
  native_client/python/client.py
Labels: documentation

#2890 Name section more explicit
  doc/TRAINING.rst
Labels: documentation

#2893 Example api net
  doc/DotNet-API.rst
  doc/DotNet-Examples.rst
  doc/conf.py
  doc/index.rst
  native_client/dotnet/DeepSpeechConsole/Program.cs
  taskcluster/docs-requirements.txt
Labels: documentation

#2894 Fix #2885: Improve ds-swig integration
  Dockerfile
  native_client/README.rst
  native_client/ctcdecode/Makefile
  native_client/definitions.mk
  native_client/java/Makefile
  native_client/javascript/Makefile
  native_client/python/Makefile
  taskcluster/.shared.yml
  taskcluster/darwin-opt-base.tyml
  taskcluster/linux-opt-base.tyml
  taskcluster/tc-all-vars.sh
  taskcluster/test-android-opt-base.tyml
  taskcluster/win-opt-base.tyml
Labels: documentation

#2929 Fix #2928: Add Python 3.7 CI coverage
  taskcluster/test-training_16k-linux-amd64-py37m-opt.yml
  taskcluster/test-training_8k-linux-amd64-py37m-opt.yml
Labels: tests

#2945 fix building ARPA file (building_lm using kenlm)
  data/lm/generate_lm.py
Labels: bug

#2954 Python TFLite tests
  taskcluster/tc-py-utils.sh
  taskcluster/tc-python_tflite-tests-prod.sh
  taskcluster/tc-python_tflite-tests.sh
  taskcluster/test-python_35_tflite_16k-darwin-amd64-opt.yml
  taskcluster/test-python_35_tflite_16k-darwin-amd64-prod-opt.yml
  taskcluster/test-python_35_tflite_16k-linux-amd64-opt.yml
  taskcluster/test-python_35_tflite_16k-win-amd64-opt.yml
  taskcluster/test-python_35_tflite_16k-win-amd64-prod-opt.yml
  taskcluster/test-python_36_tflite_16k-darwin-amd64-opt.yml
  taskcluster/test-python_36_tflite_16k-darwin-amd64-prod-opt.yml
  taskcluster/test-python_36_tflite_16k-linux-amd64-opt.yml
  taskcluster/test-python_36_tflite_16k-win-amd64-opt.yml
  taskcluster/test-python_36_tflite_16k-win-amd64-prod-opt.yml
  taskcluster/test-python_37_tflite_16k-darwin-amd64-opt.yml
  taskcluster/test-python_37_tflite_16k-darwin-amd64-prod-opt.yml
  taskcluster/test-python_37_tflite_16k-linux-amd64-opt.yml
  taskcluster/test-python_37_tflite_16k-win-amd64-opt.yml
  taskcluster/test-python_37_tflite_16k-win-amd64-prod-opt.yml
  taskcluster/test-python_37m-armbian-arm64-prod-opt.yml
  taskcluster/test-python_37m-raspbian-rpi3-prod-opt.yml
  taskcluster/test-python_38_tflite_16k-darwin-amd64-opt.yml
  taskcluster/test-python_38_tflite_16k-darwin-amd64-prod-opt.yml
  taskcluster/test-python_38_tflite_16k-linux-amd64-opt.yml
  taskcluster/test-python_38_tflite_16k-win-amd64-opt.yml
  taskcluster/test-python_38_tflite_16k-win-amd64-prod-opt.yml
Labels: tests
