Repository mozilla/DeepSpeech, pull requests merged in 2020-09, with the labels that each got.

#3319 Simplified git clone msg to prevent error reportings
  doc/TRAINING.rst
Labels: documentation

#3338 Fix #3088: Use TensorFlow 1.15.4 with CUDNN fix
  Dockerfile.train.tmpl
  doc/TRAINING.rst
  setup.py
Labels: branch:master, bug

#3340 Fix #3088: Use TensorFlow 1.15.4 with CUDNN fix
  Dockerfile.build.tmpl
  Dockerfile.train.tmpl
  doc/TRAINING.rst
  setup.py
Labels: branch:0.8, bug
