Repository mozilla/DeepSpeech, pull requests merged in 2020-03, with the labels that each got.

#2812 Show actual alphabet path in error message
  util/text.py
Labels: documentation

#2821 Add Windows CUDA CI
  taskcluster/tc-asserts.sh
  taskcluster/tc-cppwin-ds-tests.sh
  taskcluster/tc-electron-tests.sh
  taskcluster/tc-netframework-ds-tests.sh
  taskcluster/tc-node-tests.sh
  taskcluster/tc-node-utils.sh
  taskcluster/tc-python-tests.sh
  taskcluster/test-cpp_16k-win-cuda-opt.yml
  taskcluster/test-electronjs_v8.0_multiarchpkg-win-amd64-opt.yml
  taskcluster/test-electronjs_v8.0_multiarchpkg-win-cuda-opt.yml
  taskcluster/test-electronjs_v8.0_multiarchpkg-win-tflite-opt.yml.disabled
  taskcluster/test-netframework-win-cuda-opt.yml
  taskcluster/test-nodejs_13x_multiarchpkg-win-cuda-opt.yml
  taskcluster/test-python_35-win-cuda-opt.yml
  taskcluster/test-python_36-win-cuda-opt.yml
  taskcluster/test-python_37-win-cuda-opt.yml
  taskcluster/test-python_38-win-cuda-opt.yml
  taskcluster/test-win-cuda-opt-base.tyml
  taskcluster/worker.cyml
Labels: tests

#2792 Expose multiple transcriptions in "WithMetadata" API
  doc/C-API.rst
  doc/DotNet-API.rst
  doc/Java-API.rst
  doc/NodeJS-API.rst
  doc/Python-API.rst
  doc/Structs.rst
  doc/doxygen-dotnet.conf
  native_client/args.h
  native_client/client.cc
  native_client/ctcdecode/ctc_beam_search_decoder.cpp
  native_client/ctcdecode/ctc_beam_search_decoder.h
  native_client/deepspeech.cc
  native_client/deepspeech.h
  native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
  native_client/dotnet/DeepSpeechClient/DeepSpeechClient.csproj
  native_client/dotnet/DeepSpeechClient/Extensions/NativeExtensions.cs
  native_client/dotnet/DeepSpeechClient/Interfaces/IDeepSpeech.cs
  native_client/dotnet/DeepSpeechClient/Models/CandidateTranscript.cs
  native_client/dotnet/DeepSpeechClient/Models/Metadata.cs
  native_client/dotnet/DeepSpeechClient/Models/TokenMetadata.cs
  native_client/dotnet/DeepSpeechClient/NativeImp.cs
  native_client/dotnet/DeepSpeechClient/Structs/CandidateTranscript.cs
  native_client/dotnet/DeepSpeechClient/Structs/Metadata.cs
  native_client/dotnet/DeepSpeechClient/Structs/TokenMetadata.cs
  native_client/dotnet/DeepSpeechConsole/Program.cs
  native_client/java/jni/deepspeech.i
  native_client/java/libdeepspeech/src/androidTest/java/org/mozilla/deepspeech/libdeepspeech/test/BasicTest.java
  native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java
  native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech_doc/CandidateTranscript.java
  native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech_doc/DeepSpeech_Error_Codes.java
  native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech_doc/Metadata.java
  native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech_doc/README.rst
  native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech_doc/TokenMetadata.java
  native_client/javascript/client.js
  native_client/javascript/deepspeech.i
  native_client/javascript/index.js
  native_client/modelstate.cc
  native_client/modelstate.h
  native_client/python/__init__.py
  native_client/python/client.py
  native_client/python/impl.i
Labels: breaks-bw-compat

#2834 Add CI for Android 8.0, 9.0 and 10.0
  taskcluster/.shared.yml
  taskcluster/android-cache-x86_64-android-26.yml
  taskcluster/android-cache-x86_64-android-28.yml
  taskcluster/android-cache-x86_64-android-29.yml
  taskcluster/test-apk-android-26-x86_64-opt.yml
  taskcluster/test-apk-android-28-x86_64-opt.yml
  taskcluster/test-apk-android-29-x86_64-opt.yml
Labels: tests

#2843 Support building ctc_decoder wheel package on Windows system
  native_client/ctcdecode/Makefile
  native_client/ctcdecode/build_archive.py
  native_client/ctcdecode/setup.py
Labels: enhancement

#2833 Fixed sample rate logic in Python client
  native_client/python/client.py
Labels: bug
