Repository mozilla/DeepSpeech, pull requests merged in 2020-01, with the labels that each got.

#2628 Re-enable Markdown small README for Bintray hosting
  native_client/java/README.md
Labels: documentation

#2630 Ensure document vc_redist
  USING.rst
Labels: documentation

#2645 Update to TensorFlow 1.15
  Dockerfile
  requirements.txt
  taskcluster/.build.yml
  taskcluster/android-arm64-cpu-opt.yml
  taskcluster/android-armv7-cpu-opt.yml
  taskcluster/android-java-opt.yml
  taskcluster/android-x86_64-cpu-opt.yml
  taskcluster/darwin-amd64-cpu-opt.yml
  taskcluster/darwin-amd64-ctc-opt.yml
  taskcluster/darwin-amd64-tflite-opt.yml
  taskcluster/linux-amd64-cpu-opt.yml
  taskcluster/linux-amd64-ctc-opt.yml
  taskcluster/linux-amd64-gpu-opt.yml
  taskcluster/linux-amd64-tflite-opt.yml
  taskcluster/linux-arm64-cpu-opt.yml
  taskcluster/linux-rpi3-cpu-opt.yml
  taskcluster/node-package-cpu.yml
  taskcluster/node-package-gpu.yml
  taskcluster/tc-benchmark-tests.sh
  taskcluster/tc-lite_benchmark_model-ds-tests.sh
  taskcluster/tc-single-shot-inference.sh
  taskcluster/tc-train-tests.sh
  taskcluster/test-lite_benchmark_model-linux-amd64-opt.yml
  taskcluster/test-training_16k-linux-amd64-py35m-opt.yml
  taskcluster/win-amd64-cpu-opt.yml
  taskcluster/win-amd64-gpu-opt.yml
  taskcluster/win-amd64-tflite-opt.yml
Labels: breaks-bw-compat

#2644 Fix DS_EnableDecoderWithLM typo in Android bindings
  native_client/java/libdeepspeech/src/androidTest/java/org/mozilla/deepspeech/libdeepspeech/test/BasicTest.java
  native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java
Labels: breaks-bw-compat

#2666 Remove v0.6.0 TFLite prod model workaround
  taskcluster/tc-cpp_tflite-tests-prod.sh
  taskcluster/tc-node_tflite-tests-prod.sh
  taskcluster/tc-python_tflite-tests-prod.sh
  taskcluster/tc-tests-utils.sh
Labels: tests

#2700 Improve SWIG reference
  native_client/README.rst
Labels: documentation

#2706 Produce TFLite NuGet package
  taskcluster/scriptworker-task-github.yml
  taskcluster/scriptworker-task-nuget.yml
  taskcluster/tc-netframework-ds-tests.sh
  taskcluster/tc-tests-utils.sh
  taskcluster/test-netframework-win-tflite-opt.yml
  taskcluster/win-amd64-tflite-opt.yml
  taskcluster/win-build.sh
Labels: enhancement

#2705 Produce TFLite-specific NPM package
  taskcluster/node-build.sh
  taskcluster/node-package-tflite.yml
  taskcluster/scriptworker-task-github.yml
  taskcluster/scriptworker-task-npm.yml
  taskcluster/tc-tests-utils.sh
  taskcluster/test-nodejs_13x_16k_multiarchpkg-linux-tflite-opt.yml
  taskcluster/test-nodejs_13x_8k_multiarchpkg-linux-tflite-opt.yml
  taskcluster/test-nodejs_13x_multiarchpkg-darwin-tflite-opt.yml
  taskcluster/test-nodejs_13x_multiarchpkg-win-tflite-opt.yml
Labels: enhancement
