Repository mozilla/DeepSpeech, pull requests merged in 2021-02, with the labels that each got.

#3527 Fix incompatible Swift module error
  native_client/swift/deepspeech_ios.xcodeproj/project.pbxproj
  native_client/swift/deepspeech_ios_test.xcodeproj/xcshareddata/xcschemes/deepspeech_ios_test.xcscheme
Labels: bug

#3524 Added hot-word boosting doc
  doc/HotWordBoosting-Examples.rst
  doc/index.rst
  native_client/deepspeech.h
  native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
  native_client/java/libdeepspeech/src/main/java/org/deepspeech/libdeepspeech/DeepSpeechModel.java
  native_client/javascript/index.ts
  native_client/python/__init__.py
Labels: documentation

#3539 Tentative merge of SWIG master
  native_client/definitions.mk
  taskcluster/.shared.yml
  taskcluster/tc-dotnet-utils.sh
Labels: branch:master
