Repository mozilla/DeepSpeech, pull requests merged in 2021-03, with the labels that each got.

#3548 Expose .Net building doc better
  doc/BUILDING_DotNet.rst
  doc/index.rst
Labels: branch:master, documentation

#3552 Add ElectronJS v12.0
  taskcluster/.shared.yml
  taskcluster/tc-all-vars.sh
  taskcluster/test-electronjs_v12.0-darwin-amd64-opt.yml
  taskcluster/test-electronjs_v12.0-win-amd64-opt.yml
  taskcluster/test-electronjs_v12.0_16k-linux-amd64-opt.yml
  taskcluster/test-electronjs_v12.0_8k-linux-amd64-opt.yml
  taskcluster/test-electronjs_v12.0_multiarchpkg-win-amd64-opt.yml
  taskcluster/test-electronjs_v12.0_multiarchpkg-win-cuda-opt.yml
  taskcluster/test-electronjs_v12.0_multiarchpkg-win-tflite-opt.yml
Labels: branch:master, ci

#3571 Replace `remove_remote()` method with `remove` method
  training/deepspeech_training/util/io.py
Labels: branch:master, bug

#3570 Replace `remove_remote()` method with `remove` method
  training/deepspeech_training/util/io.py
Labels: branch:0.9, bug

#3577 Introduce ci_scripts/ for GitHub Actions
  .github/actions/build-tensorflow/action.yml
  .github/actions/cpp-tests/action.yml
  .github/actions/host-build/action.yml
  .github/actions/package-tensorflow/action.yml
  .github/actions/package/action.yml
  .github/actions/setup-tensorflow/action.yml
  ci_scripts/all-utils.sh
  ci_scripts/all-vars.sh
  ci_scripts/asserts.sh
  ci_scripts/build-utils.sh
  ci_scripts/cpp-bytes-ds-tests.sh
  ci_scripts/cpp-ds-tests-prod.sh
  ci_scripts/cpp-ds-tests.sh
  ci_scripts/cpp_tflite-ds-tests-prod.sh
  ci_scripts/cpp_tflite-ds-tests.sh
  ci_scripts/cpp_tflite_basic-ds-tests.sh
  ci_scripts/cppwin-ds-tests.sh
  ci_scripts/host-build.sh
  ci_scripts/package-utils.sh
  ci_scripts/package.sh
  ci_scripts/tf-build.sh
  ci_scripts/tf-package.sh
  ci_scripts/tf-setup.sh
  ci_scripts/tf-vars.sh
Labels: Transition to GitHub Actions

#3585 Fix #3578: Re-instate Python TF/TFLite tests on GitHub Actions / macOS
  .github/actions/node-build/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/macOS-amd64.yml
  ci_scripts/all-utils.sh
  ci_scripts/asserts.sh
  ci_scripts/cpp-bytes-tests.sh
  ci_scripts/cpp-tests-prod.sh
  ci_scripts/cpp-tests.sh
  ci_scripts/cpp_tflite-tests-prod.sh
  ci_scripts/cpp_tflite-tests.sh
  ci_scripts/cpp_tflite_basic-tests.sh
  ci_scripts/cppwin-tests.sh
  ci_scripts/electronjs-tests.sh
  ci_scripts/electronjs_tflite-tests.sh
  ci_scripts/node-tests-prod.sh
  ci_scripts/node-tests.sh
  ci_scripts/node_tflite-tests-prod.sh
  ci_scripts/node_tflite-tests.sh
  ci_scripts/python-tests-prod.sh
  ci_scripts/python-tests.sh
  ci_scripts/python_tflite-tests-prod.sh
  ci_scripts/python_tflite-tests.sh
Labels: Transition to GitHub Actions
