Repository mozilla/DeepSpeech, pull requests merged in 2021-01, with the labels that each got.

#3508 Docu building ctc decoder on unsupported architecture
  doc/BUILDING.rst
Labels: documentation

#3514 Set base image to ubuntu 18.04
  .taskcluster.yml
Labels: branch:master, ci

#3513 Fix decision task
  .taskcluster.yml
Labels: branch:0.9, ci
